### PR TITLE
Update CodeQL v2 And fix versions

### PR DESCRIPTION
**Pull request by jbenaventem**
❗ CodeQL Action v1 will be deprecated on December 7Th
---

image

We need to upgrade the CodeQL action to v2(#254)
Regards

### CODE REVIEW

**Comment by BALAGA-GAYATRI** [comment]
Can you please also raise a PR `releases/v1` branch which includes node_modules from where we do releases

**Comment by BALAGA-GAYATRI** [comment]
Also, you may close the ticket you raised on the Microsoft side as we are discussing and addressing it here.

**Comment by jbenaventem** [comment]
I'm not sure if I am understanding rightly and I think that I canceled this PR wrong.

I suppose that furthermore to handle that PR I need to open another PR to releases/v1

**Comment by BALAGA-GAYATRI** [comment]
Merged in https://github.com/Azure/login/pull/273
Thanks

**Pull request closed without merging**
