### PR TITLE
OIDC support for sovereign clouds

### PR DESCRIPTION
**Pull request by arnoldna**
Added OIDC support for AzureUSGovernment and AzureChinaCloud

ISSUE #257- https://github.com/Azure/login/issues/257

### CODE REVIEW

**Comment by BALAGA-GAYATRI** [comment]
@arnoldna  Thanks for the PR. Can you add more details on the tests that were done for this PR?

**Comment by arnoldna** [comment]
I have access to an AzureUSGovernment subscription and tested connectivity utilizing the following yaml:

`name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: 'AzureUSGovernment'
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd`

If there are other tests you would like to run then let me know.

**Comment by jpmicrosoft** [comment]
@BALAGA-GAYATRI Any updates on this PR?

**Comment by jpmicrosoft** [comment]
@BALAGA-GAYATRI Any updates on this PR?

**Comment by BALAGA-GAYATRI** [comment]
We are following up on the same. Will get back with the info.

**Comment by arnoldna** [comment]
@BALAGA-GAYATRI - Can we get an update on when this PR will be approved? Thanks

**Comment by some-natalie** [comment]
friendly bump on this ❤️

**Comment by devopsjesus** [comment]
Looks like the linting is failing on README - can someone please fix this and merge? PR has been open for months

**Comment by MoChilia** [comment]
Closing this pr, the feature is done in https://github.com/Azure/login/pull/321.

**Pull request closed without merging**
