### PR TITLE
Allow passwords to start with hyphen

### PR DESCRIPTION
**Pull request by johanredeploy**
I have verified this in an organization I belong to where we ran into this issue.

The password for the credential we use starts with a hyphen (`-`). With this fix the workflow run looks like this:

```
Run johanredeploy/login@v1.0.1
(node:2938) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/_actions/johanredeploy/login/v1.0.1/node_modules/actions-secret-parser/package.json' of 'lib/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Note: Azure/login action also supports OIDC login mechanism. Refer https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication for more details.
```

Admittedly I'm not really clear yet on how to publish an action for use, but this was just to verify that it actually solved the issue.

With  `@v1` from the base repository I get this insead:
```
Run azure/login@v1
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Note: Azure/login action also supports OIDC login mechanism. Refer https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication for more details.
Error: : argument --password/-p: expected one argument
```

The conclusion was drawn from looking at the [exec action](https://www.npmjs.com/package/@actions/exec) the login action is using. The examples there supply parameters as `'foo=bar'`, and that is the only format that works when passing hyphen prefixed passwords to az cli.

In these examples `$password` starts with `-`.

```sh
> az login --tenant my-tenant --service-principal -u my-principal --password $password
argument --password/-p: expected one argument
```

```sh
> az login --tenant my-tenant --service-principal -u my-principal --password "$password"
argument --password/-p: expected one argument
```

And this works:
```sh
az login --tenant my-tenant --service-principal -u my-principal --password=$password
```

### CODE REVIEW

**Comment by johanredeploy** [comment]
Any thoughts on this?

**Comment by johanredeploy** [comment]
Hello, maintainers? @BALAGA-GAYATRI, thoughts?

**Comment by shubhamdeodia** [comment]
@BALAGA-GAYATRI  even we are running into the same issue, can we please have an update.

Appreciate your help.

**Comment by BALAGA-GAYATRI** [comment]
@johanredeploy Thanks for the contribution. Can  you Please raise a corresponding PR for `releases/v1` branch as that is the release branch for this repository?

**Pull request merged**
