### PR TITLE
Improved debug output

### PR DESCRIPTION
**Pull request by bb-froggy**
The debug output is wrong, seems to be a copy & paste error. There is another debug output later on that also says 'az cli version used', so it is easy to confuse the two.

The change to line 239 seems to be some GitHub whitespace thing, I didn't intend that one, but it looks like it doesn't hurt.

### CODE REVIEW

**Comment by BALAGA-GAYATRI** [comment]
Hi, Can you please make the changes to the .js counterpart of the above file? Thanks in advance

**Comment by bb-froggy** [comment]
Done and I also rebased to the newest master

**Comment by BALAGA-GAYATRI** [comment]
Amazing!! Thanks for the quick response.

**Review by BALAGA-GAYATRI — APPROVED** [review]

**Comment by bb-froggy** [comment]
GitHub says that `releases/v1` and `master` [are entirely different commit histories](https://github.com/Azure/login/compare/master...releases/v1) and thus does not let me create a Pull Request. I did not investigate why it thinks that, as I don't know about this repository's structure.

**Pull request merged**
