### PR TITLE
Check Az Powershell version via file system

### PR DESCRIPTION
**Pull request by harvey-k**
Since so many versions of Az Powershell are installed on the virtual environments, Get-Module can be slow. Instead, obtain available Az Powershell versions directly from the filesystem. #20

### CODE REVIEW

**Comment by arjgupta** [comment]
@harvey-k this approach will not work for private runners. Your changes are specific to hosted runner and private runners will not follow the scheme of storing azure modules in a separate path. Which is why it is better to use Get-Module so as to abstract away this detail

**Comment by harvey-k** [comment]
@arjgupta  

Sorry, I don't follow why this wouldn't work for private runners. The existing Get-Module codepath was kept as a fallback:
https://github.com/Azure/login/pull/61/commits/49ef0a1ea893fe6edcbe21ea8170a48d8c0af95f#diff-6f6a3b4e60ef55a757a45b62b60aa82eb2df252eb4a96cc8601ada2411f87514R50

I understand this will not speed up private runners, but I would imagine they do not experience this issue due to only having a few powershell versions installed.

Do you want a different check for determining if the code is executing on a hosted runner?

**Comment by aksm-ms** [comment]
@harvey-k Thanks for the contribution.

Following are the possible failure cases of this approach:
- **For both Hosted and private runners**: Since folder names are used to find the latest module, there could be a mismatch between folder name and the actual version of the module installed in the folder. This issue does not occur while using `Get-Module` because it reads the version from manifest file of the module.
- **Private runners**: Although the folder az_<x.y.z> might be present inside the root folder, it could have some other contents other than the az module in which case the action fails.
Also this approach is tied to a specific folder path which is unlike PowerShell way of implementation.

Hence, at the moment, these changes will not be taken. We are currently investigating the performance issue on Login action, we will address the issue soon.

cc: @arjgupta

**Comment by aksm-ms** [comment]
Please feel free to open in case of any queries.

**Pull request closed without merging**
