### PR TITLE
Implemented Managed Identity login

### PR DESCRIPTION
**Pull request by cmatskas**
Added support for logging in using either a system assigned Managed Identity or a user-assigned Managed Identity. This allows developers to run actions against Azure using self-hosted agents on Azure VMs.

### CODE REVIEW

**Comment by cmatskas** [comment]
@aksm-ms any feedback or updates on this? /cc @BALAGA-GAYATRI

**Comment by cmatskas** [comment]
@BALAGA-GAYATRI  any updates on this? thx

**Comment by BALAGA-GAYATRI** [comment]
Hey @cmatskas !
This is in our backlog to test this change end to end and release the support for this, but it is not planned for the month of March. We are planning to look into this in the next quarter starting April.

**Comment by petebytes** [comment]
Was just looking for this - I guess I need to wait a bit.

**Comment by cmatskas** [comment]
> Hey @cmatskas ! This is in our backlog to test this change end to end and release the support for this, but it is not planned for the month of March. We are planning to look into this in the next quarter starting April. cc: @kaverma @N-Usha

Hi team, we're nearly the end of April. Any updates on when you'll be reviewing and hopefully committing this pls? Thanks

**Comment by tsbala** [comment]
Any update on when this will be merged? This is a really useful change and would massively help everyone using self-hosted agents.

**Comment by deanshackley** [comment]
Hi, need this ASAP, any chance of this getting merged in pretty please? thanks very much

**Review by Asanka98 — APPROVED** [review]

**Review by Asanka98 — APPROVED** [review]

**Review by Asanka98 — APPROVED** [review]

**Comment by tsbala** [comment]
Would be great to see movement on this. Much needed change.

**Comment by N-Usha** [comment]
Thanks for your contribution folks. And really appreciate all the patience.
Would like to update that we are currently working with Azure Active Directory (AAD) team to get the login action working for MSI (Managed Identities) + OIDC (OpenID Connect) which is currently in private preview and will be soon announced more broadly. Since we'd like to promote OIDC to be the recommended way of authentication to Azure, would like to hold off merging this PR to support MSI for non-OIDC ways of auth. 
We'll keep you updated on the release timelines of the Azure AD support for OIDC+MSI and the corresponding supporting in this azure/login action

**Pull request closed without merging**
