### PR TITLE
Use vercel/ncc

### PR DESCRIPTION
**Pull request by kWozniak-tt**
Fix for #103 #366 

Use github suggested solution to slim-down package and improve **Download** and **Unwrap** performace on self-hosted runners

Reference:
https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github
https://github.com/actions/typescript-action

image

### Before:
image

### After:
image

### CODE REVIEW

**Review by winiarskipsn — APPROVED** [review]

**Comment by kWozniak-tt** [comment]
@microsoft-github-policy-service agree

**Comment by kWozniak-tt** [comment]
@BALAGA-GAYATRI can you take a look?
Thanks

**Comment by YanaXu** [comment]
@kWozniak-tt Just FYI, we're busing on the next release now but we'll get back to your PR soon. Thanks for your contribution.

**Comment by kWozniak-tt** [comment]
@microsoft-github-policy-service agree

**Comment by MoChilia** [comment]
Thanks @kWozniak-tt for your valuable contribution on this topic! But there are still some modifications needed for using ncc. Let's track this in https://github.com/Azure/login/pull/428.

**Pull request closed without merging**
